# Generated by Django 4.1.7 on 2023-03-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_city_options_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа студента', 'verbose_name_plural': 'Группы студентов'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие (Расписание)', 'verbose_name_plural': 'Занятия (Расписание)'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запрос от студента', 'verbose_name_plural': 'Запросы от студентов'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='listeners',
            field=models.IntegerField(default=0),
        ),
    ]
