# Generated by Django 4.1.7 on 2023-03-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_group_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['title'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['discipline'], 'verbose_name': 'Занятие (Расписание)', 'verbose_name_plural': 'Занятия (Расписание)'},
        ),
        migrations.AddField(
            model_name='request',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
