# Generated by Django 4.1.7 on 2023-03-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_discipline_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
    ]
